baseURL = "https://jorgeml.me/"
languageCode = "en-gb"
title = "it's my life"
theme = "hyde"
MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
#Paginate = 9 # this is set low for demonstrating with dummy content. Set to a higher number
disqusShortname = "jorgeml"
googleAnalytics = "UA-146441738-1"
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  description = "it's a wonderful, wonderful life"
  #copyright = "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\"><img alt=\"Creative Commons Licence\" style=\"border-width:0\" src=\"https://i.creativecommons.org/l/by-sa/4.0/80x15.png\" /></a> This work is licensed under a <a rel=\"license\" href=\"http://creativecommons.org/licenses/by-sa/4.0/\" class=\"hover-white no-underline white-70 dn dib-ns\">Creative Commons Attribution-ShareAlike 4.0 International License</a>."
  copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  gravatar = "jorgeml@jorgeml.me"
  facebook = ""
  twitter = "https://twitter.com/jorgeml"
  instagram = "https://www.instagram.com/jorge__martinez_lopez/"
  youtube = ""
  github = "https://github.com/jorgeml"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jorgeml/"
  mastodon = "https://mastodon.social/@jorgeml"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  #background_color_class = "bg-black"
  #body_classes = "roboto bg-near-white"
  featured_image = "/images/hero-image.jpg"
  #recent_posts_number = 2
  themeColor = "theme-base-0f"

