baseURL = "https://jorgeml.me/"
languageCode = "en-GB"
title = "my name is Jorge"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

SectionPagesMenu = "main"
Paginate = 10
DisqusShortname = "jorgeml"
googleAnalytics = "UA-146441738-1"
enableRobotsTXT = true
enableEmoji     = true
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
  
[params]
  homeSubtitle = "and one day I'll have a proper blog."
  copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
  license = "CC BY-SA 4.0"
  licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  gravatar = "jorgeml@jorgeml.me"
  disableReadOtherPosts = false
  enableSharingButtons = true
  
  [params.footer]
    trademark = false
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = ["Powered by <a href=\"http://gohugo.io\">Hugo</a>",
            "Made with &#10084; by <a href=\"https://github.com/rhazdon\">Djordje Atlialp</a>"]

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/jorgeml"

  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/jorge__martinez_lopez/"

  [[params.social]]
    name = "github"
    url = "https://github.com/jorgeml"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/jorgeml/"

  [[params.social]]
    name = "mastodon"
    url = "https://mastodon.social/@jorgeml"

  [[params.social]]
    name = "matrix"
    url = "https://matrix.to/#/@jorgeml:matrix.org"

  [[params.social]]
    name = "reddit"
    url = "https://www.reddit.com/user/jorgeml"

[languages]
 [languages.en]
    title = "my name is Jorge"
    subtitle = "one day I'll have a proper blog"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"
 [languages.es]
    title = "mi nombre es Jorge"
    subtitle = "algún día tendré un blog"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Leer otras entradas"


